### ISSUE TITLE
Todo list for v2

### ISSUE THREAD

**Issue by georgd** [georgd/EB-Garamond#179]
Opentype features

- [ ] various features with /f.deu (https://github.com/octaviopardo/EBGaramond12/issues/38, https://github.com/octaviopardo/EBGaramond12/issues/23)
- [ ] remove latin locale (https://github.com/octaviopardo/EBGaramond12/issues/31)
- [ ] rearrange ligature features to match the original behaviour (https://github.com/octaviopardo/EBGaramond12/issues/22, https://github.com/octaviopardo/EBGaramond12/issues/20)
- [ ] re-implement calt (https://github.com/octaviopardo/EBGaramond12/issues/4)
- [ ] re-add /Q.long feature (addresses https://github.com/octaviopardo/EBGaramond12/issues/48)
- [ ] re-add cvXX features
- [ ] smallcaps table (https://github.com/octaviopardo/EBGaramond12/issues/41, https://github.com/octaviopardo/EBGaramond12/issues/19)

Glyphs

- [ ] remove ball terminal from /Q.long in the roman fonts (addresses https://github.com/octaviopardo/EBGaramond12/issues/48)
- [ ] return to more open designs in /f and /longs in italic fonts
- [ ] fix errors in paths (https://github.com/octaviopardo/EBGaramond12/issues/45, https://github.com/octaviopardo/EBGaramond12/issues/24)
- [ ] add /uni202F (https://github.com/octaviopardo/EBGaramond12/issues/37)
- [ ] correct vertical placement of mathematical operators (https://github.com/octaviopardo/EBGaramond12/issues/33)
- [ ] improve uhorn/ohorn (https://github.com/octaviopardo/EBGaramond12/issues/18)
- [ ] add /uni2052 (https://github.com/octaviopardo/EBGaramond12/issues/17)
- [ ] add poetic meter glyphs (/uni23D1 to /uni23D6)

Diacritics

- [ ] (re-)add necessary anchors (https://github.com/octaviopardo/EBGaramond12/issues/42, https://github.com/octaviopardo/EBGaramond12/issues/19)
- [ ] add decomposition to smallcaps and petitecaps features (https://github.com/octaviopardo/EBGaramond12/issues/35, https://github.com/octaviopardo/EBGaramond12/issues/19)

Fix kerning issues

- [ ] https://github.com/octaviopardo/EBGaramond12/issues/46
- [ ] https://github.com/octaviopardo/EBGaramond12/issues/36

Longer term:

- https://github.com/octaviopardo/EBGaramond12/issues/30
- https://github.com/octaviopardo/EBGaramond12/issues/26

**Comment by georgd** [comment]
For those interested: I’m currently working on the merge tasks. The progress looks good, so far, but the biggest tasks are still ahead of me, re-adding all the missing anchors and revisiting the kerning. 

When the tasks are done, v2 shall be released. The next steps are to reduce the backlog of issues (minor additions of glyphs), to bring the Italics to par with the Romans and then start working on the optical axis. The latter will probably lead up to a v3.

**Comment by davelab6** [comment]
@georgd how does this relate to the https://github.com/octaviopardo/EBGaramond12 version? :)

**Comment by georgd** [comment]
@davelab6 I want to reconcile both versions, mainly using Octavio's splines but readding the complete feature set. On the way there I want to fix issues reported on Octavio's as well as the ones reported here.

I've done some work on the glyphs already and a good amount of the features but I'm stuck with otf <> fontforge round-tripping. Somewhere in the process the splines were damaged...
